### ISSUE TITLE
Null - Total threads

### ISSUE THREAD

**Issue by andresrubiop** [GMAP/NPB-CPP#2]
Hello I am running your version of NPB it is really nice. Just a little bug the final report shows.

Total threads   =                   (null)

**Comment by dalvangriebler** [comment]
Hello @andresrubiop, are you sure that you set up the number of threads?

For instance:
```
export OMP_NUM_THREADS=4
```

can you share which benchmark is presenting this bug?

**Comment by dalvangriebler** [comment]
This issue can now be close due to this commit https://github.com/GMAP/NPB-CPP/commit/2f77a1bce83c4efda56c4bafb555bcf9abe85dd2, which covered this small bug.
